import { contextBridge, ipcRenderer, type IpcRendererEvent } from "electron";

// IPC 白名单：渲染进程只能调用这些主进程通道。
// 新增 IPC 时必须同时在此登记，否则渲染层调用会被拒绝。
const ALLOWED_IPC_CHANNELS = [
  "add_workspace_project",
  "archive_codex_thread",
  "archive_local_ai_session",
  "attach_provider_session",
  "batch_write_codex_config",
  "check_app_update",
  "check_server_app_update",
  "choose_chat_file_attachments",
  "choose_workspace_project",
  "clear_codex_thread_goal",
  "clear_credentials",
  "codex_start_review",
  "compact_codex_thread",
  "create_ai_session",
  "delete_codex_thread",
  "delete_local_ai_session",
  "detect_ai_providers",
  "export_text_file",
  "fork_codex_thread",
  "get_ai_activity_summary",
  "get_app_version",
  "get_cloud_config",
  "get_codex_approval_mode",
  "get_codex_thread_goal",
  "get_desktop_runtime_info",
  "get_local_ai_trace",
  "get_npm_registry",
  "get_project_environment",
  "get_shell_buffer",
  "get_token_usage_summary",
  "get_update_download_size",
  "git_add_all",
  "git_commit",
  "git_pull",
  "git_push",
  "git_status_detail",
  "git_worktree_add",
  "git_worktree_list",
  "git_worktree_remove",
  "github_login_poll",
  "github_login_start",
  "google_login_poll",
  "google_login_start",
  "has_live_ai_chat",
  "install_app_update",
  "is_shell_live",
  "list_ai_providers",
  "list_chatroom_roles",
  "list_codex_features",
  "list_codex_hooks",
  "list_codex_mcp_servers",
  "list_codex_models",
  "list_codex_permission_profiles",
  "list_codex_skills",
  "list_codex_threads",
  "list_local_ai_history",
  "list_local_ai_sessions",
  "list_mimo_config_options",
  "list_opencode_config_options",
  "list_pipeline_templates",
  "list_project_files",
  "list_provider_sessions",
  "list_sessions",
  "list_workspace_projects",
  "load_credentials",
  "login_desktop",
  "logout_desktop",
  "migrate_claude_mcp",
  "open_external_url",
  "open_project_html_in_browser",
  "open_project_in_file_manager",
  "open_project_with",
  "open_session_in_new_window",
  "probe_npm_registries",
  "publish_ai_run_settings",
  "read_clipboard_image",
  "read_codex_config",
  "read_codex_mcp_resource",
  "read_codex_thread",
  "read_project_file_for_viewer",
  "read_project_file_preview",
  "reload_codex_mcp_servers",
  "remove_workspace_project",
  "rename_ai_session",
  "rename_codex_thread",
  "rename_local_ai_session",
  "rename_workspace_project",
  "resize_shell",
  "respond_ai_approval",
  "respond_codex_approval",
  "respond_codex_user_input",
  "restart_ai_session",
  "run_ai_chat",
  "run_chatroom_turn",
  "run_codex_chat",
  "run_pipeline_chat",
  "run_provider_action",
  "save_credentials",
  "scan_claude_config",
  "search_ai_sessions",
  "send_shell_input",
  "set_codex_feature",
  "set_codex_skill_enabled",
  "set_codex_skills_extra_roots",
  "set_codex_thread_goal",
  "set_npm_registry",
  "start_codex_mcp_oauth",
  "start_shell_pty",
  "steer_codex_chat",
  "stop_ai_chat",
  "stop_shell_pty",
  "warmup_ai_session",
  "warmup_codex_session",
  "write_codex_config_value"
] as const;

const api = {
  invoke: (channel: string, ...args: unknown[]) => {
    if (!(ALLOWED_IPC_CHANNELS as readonly string[]).includes(channel)) {
      return Promise.reject(new Error(`IPC channel "${channel}" is not in the allowlist`));
    }
    return ipcRenderer.invoke(channel, args);
  },
  on: (channel: string, listener: (...args: unknown[]) => void) => {
    const wrapped = (_event: IpcRendererEvent, ...args: unknown[]) => listener(...args);
    ipcRenderer.on(channel, wrapped);
    return () => ipcRenderer.removeListener(channel, wrapped);
  },
};

contextBridge.exposeInMainWorld("desktop", api);
